name: Docker Build

on:
  push:
    branches:
      - master
      - internal/docker

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Java 11 compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn clean install

      - name: Docker Build & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: eedu/user-ms
          tags: latest
